### ISSUE TITLE
你好，使用你的项目关于WebSocket有一个问题

### ISSUE THREAD

**Issue by gaopengmanzhuo** [js1688/cat#2]
websocket.js: 中修改了端口
var socket = new WebSocket("ws://localhost:8080/opencv/index");

启动时，控制台打出
“WebSocket,建立连接成功
websocket.js:42 WebSocket,已关闭” 

报这个错误 ：
WebSocket is already in CLOSING or CLOSED state 

也就是说WebSocket开启后我没等使用，直接就关闭了！
当我在调用左上角“创建群组”时就会报错。

另外在右上角进来页面的时候，并没有给我分配用户名，显示为空白 。
我使用了你网站的页面，发面每次刷新后是会分配一个用户名的。
不知道我这为什么没有用户名，和Js报错。

**Comment by js1688** [comment]
你好！
没有完整的错误信息,无法判断为什么在建立socket后立即断开, 创建群组 以及 分配个人用户名 是需要向后台申请,你的socket是不可用的自然无法正确申请一些信息,现在主要的问题则是socket为什么会自动断开,你可以关注一下后台断开的异常,或者在前端断开后再次发起连接socket来解决这些问题。

**Comment by wang614340595** [comment]
您好！项目中index.js页面中的js/css/img路径前面多加了/cat 路径，修改后，才可以正常访问。websocket路径使用的是演示路径，需要调整成本地路径websocket.js var socket = new WebSocket("ws://127.0.0.1:8080/index");

**Comment by js1688** [comment]
@wang614340595 这是因为你使用中间件启动项目的时候没有指定项目的乡下文造成的,比如tomcat默认会将webapps下的目录名称当作项目上下文,如果是eclips中的jetty启动它默认是/（斜杠） 为上下文，这就不需要在访问的前面加cat项目上下文了

**Comment by leeyx1994** [comment]
您好！多人视频中为什么不能看见全部的视频？如果打开了视频本地视频是可以看到的，远程视频的div中可以看见对方的sessionid，但是视频不能显示

**Comment by js1688** [comment]
@leeyx1994 你看一下没有视频的那个是否有点击开始视频,或者它是否有摄像头等设备。

**Comment by leeyx1994** [comment]
开了的，每个用户的本地视频均正常显示视频了
